#pragma config(Motor,  port2,           leftMotor1,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           leftMotor2,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           rightMotor1,   tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           rightMotor2,   tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           flipper,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           spinnythingy,  tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          flipperShaft,  tmotorVex393_HBridge, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*        Description: Competition template for VEX EDR                      */
/*                                                                           */
/*---------------------------------------------------------------------------*/

// This code is for the VEX cortex platform
#pragma platform(VEX2)

// Select Download method as "competition"
#pragma competitionControl(Competition)

//Main competition background code...do not modify!
#include "Vex_Competition_Includes.c"

/*---------------------------------------------------------------------------*/
/*                          Pre-Autonomous Functions                         */
/*                                                                           */
/*  You may want to perform some actions before the competition starts.      */
/*  Do them in the following function.  You must return from this function   */
/*  or the autonomous and usercontrol tasks will not be started.  This       */
/*  function is only called once after the cortex has been powered on and    */
/*  not every time that the robot is disabled.                               */
/*---------------------------------------------------------------------------*/

const short leftButton = 1;
const short centerButton = 2;
const short rightButton = 4;
int count = 0;

void waitForPress() {
while(nLCDButtons == 0){}
wait1Msec(5);
}

void waitForRelease() {
while(nLCDButtons != 0){}
wait1Msec(5);
}
void setMotors(float speedLeft, float speedRight) {
	motor[rightMotor1] = speedRight;
	motor[rightMotor2] = speedRight;
	motor[leftMotor1] = speedLeft;
	motor[leftMotor2] = speedLeft;
}

void pre_auton() {
	int count = 0;

	//------------- Beginning of User Interface Code ---------------
	//Clear LCD
	clearLCDLine(0);
	clearLCDLine(1);
	//Loop while center button is not pressed
	while(nLCDButtons != centerButton) {
		//Switch case that allows the user to choose from 4 different options
		switch(count) {
		case 0:
			//Display first choice
			displayLCDCenteredString(0, "No Movements");
			displayLCDCenteredString(1, "<         Enter        >");
			waitForPress();
			//Increment or decrement "count" based on button press
			if(nLCDButtons == leftButton) {
				waitForRelease();
				count = 3;
			}
			else if(nLCDButtons == rightButton) {
				waitForRelease();
				count++;
			}
			break;
		case 1:
			//Display second choice
			displayLCDCenteredString(0, "Left Side Fwd");
			displayLCDCenteredString(1, "<         Enter        >");
			waitForPress();
			//Increment or decrement "count" based on button press
			if(nLCDButtons == leftButton) {
				waitForRelease();
				count--;
			}
			else if(nLCDButtons == rightButton) {
				waitForRelease();
				count++;
			}
			break;
		case 2:
			//Display third choice
			displayLCDCenteredString(0, "Right Side Flag");
			displayLCDCenteredString(1, "<         Enter        >");
			waitForPress();
			//Increment or decrement "count" based on button press
			if(nLCDButtons == leftButton) {
				waitForRelease();
				count--;
			}
			else if(nLCDButtons == rightButton) {
				waitForRelease();
				count++;
			}
			break;
		case 3:
			//Display fourth choice
			displayLCDCenteredString(0, "N/A");
			displayLCDCenteredString(1, "<         Enter        >");
			waitForPress();
			//Increment or decrement "count" based on button press
			if(nLCDButtons == leftButton) {
				waitForRelease();
				count--;
			}
			else if(nLCDButtons == rightButton) {
				waitForRelease();
				count = 0;
			}
			break;
		default:
			count = 0;
			break;
		}
	}
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              Autonomous Task                              */
/*                                                                           */
/*  This task is used to control your robot during the autonomous phase of   */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task autonomous() {
	clearLCDLine(0);
	clearLCDLine(1);
	switch(count) {
	
	case 1: //Left Side Forward
	setMotors(-128,-128);
	motor[spinnythingy] = 128;
	wait1Msec(2000);
	setMotors(0,0);
	wait1Msec(2000);
	motor[spinnythingy] = 0;
	break;
	
	case 2: // Right Side Flag
	motor[flipper] = 128;
	wait1Msec(1500);
	motor[flipper] = 0;
	setMotors(128,128);
	break;
	
	case 3:
	
	break;
	
	case 0: default:
	AutonomousCodePlaceholderForTesting();
	break;
	}
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              User Control Task                            */
/*                                                                           */
/*  This task is used to control your robot during the user control phase of */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task usercontrol()
{
	int finalA = 128;
	while (true) {
		motor[leftMotor1] = -vexRT[Ch3] - (vexRT[Btn8U] * finalA);// + vexRT[Ch4];
		motor[leftMotor2] = -vexRT[Ch3] - (vexRT[Btn8U] * finalA);// + vexRT[Ch4];
		motor[rightMotor1] = -vexRT[Ch2] - (vexRT[Btn8U] * finalA);// - vexRT[Ch4];
		motor[rightMotor2] = -vexRT[Ch2] - (vexRT[Btn8U] * finalA);// - vexRT[Ch4]; //for tank controls

		motor[flipperShaft] = (vexRT[Btn6U] - vexRT[Btn6D])*128;
		motor[flipper] = (vexRT[Btn5U] - vexRT[Btn5D])*128*2/3;
		motor[spinnythingy] = (vexRT[Btn8U] + vexRT[Btn8D]) * 128;
		//motor[rotX] = (vexRT[Btn7R]*64)-(vexRT[Btn7L]*128);
		//motor[rotY1] = (vexRT[Btn7U]*40)-(vexRT[Btn7D]*40);
		//motor[rotY2] = (vexRT[Btn7U]*40)-(vexRT[Btn7D]*40);
		//motor[flipper] = vexRT[Ch2]/3;
	}
}
