#pragma config(Motor,  port2,           leftMotor1,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           leftMotor2,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           rightMotor1,   tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           rightMotor2,   tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           flipper,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           spinnythingy,  tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          flipperMover,  tmotorVex393_HBridge, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*        Description: Competition template for VEX EDR                      */
/*                                                                           */
/*---------------------------------------------------------------------------*/

// This code is for the VEX cortex platform
#pragma platform(VEX2)

// Select Download method as "competition"
#pragma competitionControl(Competition)

//Main competition background code...do not modify!
#include "Vex_Competition_Includes.c"

/*---------------------------------------------------------------------------*/
/*                          Pre-Autonomous Functions                         */
/*                                                                           */
/*  You may want to perform some actions before the competition starts.      */
/*  Do them in the following function.  You must return from this function   */
/*  or the autonomous and usercontrol tasks will not be started.  This       */
/*  function is only called once after the cortex has been powered on and    */
/*  not every time that the robot is disabled.                               */
/*---------------------------------------------------------------------------*/

void pre_auton()
{
	




	bStopTasksBetweenModes = true;
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              Autonomous Task                              */
/*                                                                           */
/*  This task is used to control your robot during the autonomous phase of   */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task autonomous()
{
	/*
	
	
	
	
	
	
	*/
	AutonomousCodePlaceholderForTesting();
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              User Control Task                            */
/*                                                                           */
/*  This task is used to control your robot during the user control phase of */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task usercontrol()
{
	int finalA = 128;
	string battery;
	while (true) {
		motor[leftMotor1] = -vexRT[Ch3] - (vexRT[Btn8U] * finalA);// + vexRT[Ch4];
		motor[leftMotor2] = -vexRT[Ch3] - (vexRT[Btn8U] * finalA);// + vexRT[Ch4];
		setMotors(-vexRT[Ch3] - (vexRT[Btn8U]*finalA);
		motor[rightMotor1] = -vexRT[Ch2] - (vexRT[Btn8U] * finalA);// - vexRT[Ch4];
		motor[rightMotor2] = -vexRT[Ch2] - (vexRT[Btn8U] * finalA);// - vexRT[Ch4]; //for tank controls

		motor[flipperMover] = (vexRT[Btn6U] - vexRT[Btn6D])*128;
		motor[flipper] = (vexRT[Btn5U] - vexRT[Btn5D])*128*2/3;
		motor[spinnythingy] = (vexRT[Btn8U] + vexRT[Btn8D]) * 128;
		
		/*displayLCDString(0, 0, "Battery: ");
		sprintf(battery, "%1.2fV", nImmediateBatteryLevel/1000.0);
		displayNextLCDString(battery);*/
 
		//motor[rotX] = (vexRT[Btn7R]*64)-(vexRT[Btn7L]*128);
		//motor[rotY1] = (vexRT[Btn7U]*40)-(vexRT[Btn7D]*40);
		//motor[rotY2] = (vexRT[Btn7U]*40)-(vexRT[Btn7D]*40);
		//motor[flipper] = vexRT[Ch2]/3;
		
	}
}
void setMotors(float speedRight, float speedLeft) {
	motor[rightMotor1] = speedRight;
	motor[rightMotor2] = speedRight;
	motor[leftMotor1] = speedLeft;
	motor[leftMotor2] = speedLeft;
}
